# Site settings
title: "Jacob Hobbie"
description: "The philisophical, theological, technical, and fun thoughts of a software developer"

author: Jacob Hobbie
email: contact@jacobhobbie.com

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jacobhobbie.com" # the base hostname & protocol for your site

google_analytics_id: UA-61802753-2
disqus_id:

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title.html

sass:
    style: compressed

exclude: [vendor]