# Site Settings
title: Jacob Hobbie
email: contact@jacobhobbie.com
description: >-
  I'm Jacob Hobbie. I type code, I think a lot about the future, and I
  try to make the world a little better every single day.
baseurl: ""
url: "https://jacobhobbie.com"

# Social Settings
twitter_username: HobbieJacob
github_username: HobbieJ
linkedin_username: hobbiej

# Build Settings
markdown: kramdown
timezone: America/Chicago
theme: Hobbies

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Default Exclude From Processing List
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/