version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:latest
    working_directory: ~/HobbieBlog
    environment:
      - HOBBIEBLOG_BUILD_DIR: ~/HobbieBlog/Build
    steps:
      - checkout
      - run: 
          name: Check Jekyll Dependencies
          command: ruby -v && gem -v && gcc -v && g++ -v && make -v
      - run: 
          name: Install Jekyll & HobbieBlog Dependencies
          command: bundle install
      - run: 
          name: Build HobbieBlog
          command: jekyll build --destination $HOBBIEBLOG_BUILD_DIR
      - persist_to_workspace:
          root: .
          paths:
            - Build
  deploy:
    docker:
      - image: circleci/ruby:latest
    working_directory: ~/HobbieBlog
    environment:
     - HOBBIEBLOG_BUILD_DIR: Build
     - PUBLIC_KEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDveatqaFMzMt0/6oPZUhT/1gKMXklMTLxte1ieBjUuGsFfaQob3iuLf6+aRqK5XAZb8kBwjin4RyiAqqveliZS+6io8Wnw9YGajY74aYKyspERRMdT0aQ8NlNo34gpodhL0N4T1NFL+IjIIQjGSEGjNVOGOMEYwJvMi905lt+UiSwkqdlPSFFgoaX02zWsnh9rwmo1fy3v6xlpnh3cf5+0UkWK5E9/YwVXbBxRp7P7U0mFQQvRzqhhWXQ2DlFmqKny39J+9w9JeJZYLIvYH465WeI1TxWvV0XTWw6Us2pmFTBLLh8GzAgguJbTxGk6kEXLfdlLXfT/hJjyYZ8j/XF/ LinkChef@Athena
     - HOBBIEJ_SITE_DIR: /var/www/HobbieJ
     - SITE_LOGIN: hobbiej@jacobhobbie.com
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Change to Build Directory
          command: cd $HOBBIEBLOG_BUILD_DIR
      - run:
          name: Copy Public Key
          command: echo '$PUBLIC_KEY' >> ~/.ssh/known_hosts
      - run:
          name: Connect over SFTP
          command: sftp $SITE_LOGIN
      - run:
          name: Change Directory to Website Folder
          command: cd $HOBBIEJ_SITE_DIR
      - run:
          name: Clean Website Folder
          command: rm -rf $HOBBIEJ_SITE_DIR/*
      - run:
          name: Copy New Website to Website Folder
          command: put -r $HOBBIEBLOG_BUILD_DIR

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master