version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:latest
    working_directory: ~/HobbieBlog
    environment:
      - HOBBIEBLOG_BUILD_DIR: ~/HobbieBlog/Build
    steps:
      - checkout
      - run: 
          name: Check Jekyll Dependencies
          command: ruby -v && gem -v && gcc -v && g++ -v && make -v
      - run: 
          name: Install Jekyll & HobbieBlog Dependencies
          command: bundle install
      - run: 
          name: Build HobbieBlog
          command: jekyll build --destination $HOBBIEBLOG_BUILD_DIR
  deploy:
    docker:
      - image: circleci/ruby:latest
    working_directory: ~/HobbieBlog
    environment:
     - HOBBIEBLOG_BUILD_DIR: ~/HobbieBlog/Build