version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:latest
    working_directory: ~/HobbieBlog
    environment:
      - HOBBIEBLOG_BUILD_DIR: ~/HobbieBlog/Build
      - RELATIVE_BUILD_DIR: /Build
    steps:
      - checkout
      - run: 
          name: Check Jekyll Dependencies
          command: ruby -v && gem -v && gcc -v && g++ -v && make -v
      - run: 
          name: Install Jekyll & HobbieBlog Dependencies
          command: bundle install
      - run: 
          name: Build HobbieBlog
          command: jekyll build --destination $HOBBIEBLOG_BUILD_DIR
      - persist_to_workspace:
          root: $RELATIVE_BUILD_DIR
  deploy:
    docker:
      - image: circleci/ruby:latest
    working_directory: ~/HobbieBlog
    environment:
     - HOBBIEBLOG_BUILD_DIR: ~/HobbieBlog/Build
    steps:
      - attach_workspace:
          at: $HOBBIEBLOG_BUILD_DIR
      - run:
          name: Change to Build Directory
          command: cd $HOBBIEBLOG_BUILD_DIR
      - run:
          name: Connect over SFTP
          command: sftp hobbiej@jacobhobbie.com
      - run:
          name: Change Directory to Website Folder
          command: cd /var/www/HobbieJ
      - run:
          name: Clean Website Folder
          command: rm -rf /var/www/HobbieJ/*
      - run:
          name: Copy New Website to Website Folder
          command: put -r $HOBBIEBLOG_BUILD_DIR

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master