version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:latest
    working_directory: ~/HobbieBlog
    environment:
      - HOBBIEBLOG_BUILD_DIR: ~/HobbieBlog/Build
    steps:
      - checkout
      - run: 
          name: Check Jekyll Dependencies
          command: ruby -v && gem -v && gcc -v && g++ -v && make -v
      - run: 
          name: Install Jekyll & HobbieBlog Dependencies
          command: bundle install
      - run: 
          name: Build HobbieBlog
          command: jekyll build --destination $HOBBIEBLOG_BUILD_DIR
      - persist_to_workspace:
          root: .
          paths:
            - Build
  deploy:
    docker:
      - image: circleci/ruby:latest
    working_directory: ~/HobbieBlog
    environment:
     - HOBBIEBLOG_BUILD_DIR: ~/HobbieBlog/Build
     - HOBBIEJ_SITE_DIR: /var/www/HobbieJ
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Print Public Keys to known_hosts
          command: printf "$PUB_KEY_ONE\n$PUB_KEY_TWO" > .ssh/known_hosts
      - run:
          name: Change to Build Directory
          command: cd $HOBBIEBLOG_BUILD_DIR
      - run:
          name: Connect over SSH
          command: ssh $SSH_USER@$SSH_HOST
      - run:
          name: Change Directory to Website Folder
          command: cd $HOBBIEJ_SITE_DIR
      - run:
          name: Clean Website Folder
          command: rm -rf $HOBBIEJ_SITE_DIR/*
      - run:
          name: Copy New Website to Website Folder
          command: put -r $HOBBIEBLOG_BUILD_DIR

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master